### ISSUE TITLE
Specify license

### ISSUE THREAD

**Issue by Kagami** [ob-ivan/KoreanTranscription#2]
Hi!

I love your project and would like to use part of the code in my (open source) library. Would you be so kind to explicitly mention license?

Thank you.

**Comment by Kagami** [comment]
Thanks!

**Comment by ob-ivan** [comment]
You're welcome! Would you mind sharing a link to your project?

**Comment by Kagami** [comment]
It's https://github.com/Kagami/kpopnet
I'm going to add russian transliteration for hangul names in profiles.

**Comment by Kagami** [comment]
Ported (partially) to JS library: https://github.com/Kagami/ruhangul
